# SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: OpenMDW-1.1

# Combined Sample Loaders
# Auto-generated script combining all sample_loader.py files (Dont edit this file! Edit the projects/cosmos/reasoning/v1/scripts/create_sample_loader_and_part_filter_file.py instead)

import io

import torch
from PIL import Image

from cosmos_framework.utils import log
from cosmos_framework.data.vfm.data_sources.vlm.nvlm import data_path_mapping

# This file was automatically generated by `nvgpt4 data prepare`.
# import torch


def sample_loader_0(raw: dict) -> dict:  # Note: Images are already decoded to tensors
    if "text" in raw:
        caption = raw["text"]
    else:
        caption = raw["json"]["caption"]
    return dict(
        __key__=raw["__key__"],
        image=raw["jpg"],  # expected type: torch.Tensor
        caption=caption,  # expected type: str
    )


def part_filter_0(part: str) -> bool:
    # E.g. if your dataset contains jpeg, txt and json, but you won't use json,
    # remove it from the list, such that it is not decoded. If you need all, keep as is
    return part in ("json", "jpg", "text")


# Loader for: /lustre/fsw/portfolios/llmservice/users/zhuoliny/extended-sci/data/merged/CoT
# This file was automatically generated by `energon prepare`.


def sample_loader_1(raw: dict) -> dict:  # Note: Images are already decoded to tensors
    json_item = raw["json"]
    images = [raw["jpg"]]

    return dict(
        __key__="llava-{}".format(raw["__key__"]),
        images=images,
        texts=json_item["conversations"],
        similarity_matrix=None,
    )


def part_filter_1(part: str) -> bool:
    # E.g. if your dataset contains jpeg, txt and json, but you won't use json,
    # remove it from the list, such that it is not decoded. If you need all, keep as is
    return part in ("jpg", "json")


# Loader for: /lustre/fsw/portfolios/llmservice/users/zhuoliny/extended-sci/data/merged/single-choice
# This file was automatically generated by `energon prepare`.


def sample_loader_2(raw: dict) -> dict:  # Note: Images are already decoded to tensors
    json_item = raw["json"]
    images = [raw["jpg"]]

    return dict(
        __key__="llava-{}".format(raw["__key__"]),
        images=images,
        texts=json_item["conversations"],
        similarity_matrix=None,
    )


def part_filter_2(part: str) -> bool:
    # E.g. if your dataset contains jpeg, txt and json, but you won't use json,
    # remove it from the list, such that it is not decoded. If you need all, keep as is
    return part in ("jpg", "json")


# Loader for: /lustre/fsw/portfolios/llmservice/users/zhuoliny/extended-sci/data/extended-sci-3/CoT
# This file was automatically generated by `energon prepare`.


def sample_loader_3(raw: dict) -> dict:  # Note: Images are already decoded to tensors
    json_item = raw["json"]
    images = [raw["jpg"]]

    return dict(
        __key__="llava-{}".format(raw["__key__"]),
        images=images,
        texts=json_item["conversations"],
        similarity_matrix=None,
    )


def part_filter_3(part: str) -> bool:
    # E.g. if your dataset contains jpeg, txt and json, but you won't use json,
    # remove it from the list, such that it is not decoded. If you need all, keep as is
    return part in ("jpg", "json")


# Loader for: /lustre/fsw/portfolios/llmservice/users/zhuoliny/extended-sci/data/extended-sci-3/single-choice
# This file was automatically generated by `energon prepare`.


def sample_loader_4(raw: dict) -> dict:  # Note: Images are already decoded to tensors
    json_item = raw["json"]
    images = [raw["jpg"]]

    return dict(
        __key__="llava-{}".format(raw["__key__"]),
        images=images,
        texts=json_item["conversations"],
        similarity_matrix=None,
    )


def part_filter_4(part: str) -> bool:
    # E.g. if your dataset contains jpeg, txt and json, but you won't use json,
    # remove it from the list, such that it is not decoded. If you need all, keep as is
    return part in ("jpg", "json")


# Loader for: /lustre/fsw/portfolios/llmservice/projects/llmservice_nlp_fm/datasets/nvlm/wdai/data/SceMQA_processed
# This file was automatically generated by `nvgpt4 data prepare`.


def sample_loader_5(raw: dict) -> dict:  # Note: Images are already decoded to tensors
    json_item = raw["json"]
    images = [raw["jpg"]]

    return dict(
        __key__="llava-{}".format(raw["__key__"]),
        images=images,
        texts=json_item["conversations"],
        similarity_matrix=None,
    )


def part_filter_5(part: str) -> bool:
    # E.g. if your dataset contains jpeg, txt and json, but you won't use json,
    # remove it from the list, such that it is not decoded. If you need all, keep as is
    return part in ("json", "jpg")


# Loader for: /lustre/fsw/portfolios/llmservice/projects/llmservice_nlp_fm/datasets/nvlm/wdai/data/vqa_collection_doc_text_st_chart_scale_textbook_LRV_Screen
# This file was automatically generated by `nvgpt4 data prepare`.


def sample_loader_6(raw: dict) -> dict:  # Note: Images are already decoded to tensors
    json_item = raw["json"]

    key = raw["__key__"]
    if "docvqa" in key:
        context = json_item["question"]
        answers = json_item["answers"]
        image = raw["jpg"]
        answer_weights = json_item["answer_weights"]
    elif "textvqa" in key or "lrv_instruct" in key:
        context = json_item["question"]
        answers = json_item["answer"]
        image = raw["jpg"]
        answer_weights = None
    elif "stvqa" in key:
        context = json_item["question"]
        answers = json_item["answers"]
        image = raw["jpg"]
        answer_weights = [1.0] * len(json_item["answers"])
    elif "chartqa" in key:
        context = json_item["query"]
        answers = json_item["label"]
        image = raw["png"]
        answer_weights = None
    elif "screenqa" in key:
        image = raw["jpg"]
        context = json_item["question"]
        answers = json_item["ground_truth"]
        answer_weights = [1.0] * len(json_item["ground_truth"])
    elif "HME100K" in key:
        image = raw["jpg"]
        context = "Please write out the expression of the formula in the image using LaTeX format."
        answers = json_item["latex_formula"]
        answer_weights = None
    else:  # scale, textbook
        image = raw["jpg"]
        context = json_item["question"]
        answers = json_item["answer"]
        answer_weights = None

    return dict(
        __key__=key,
        image=image,
        context=context,
        answers=answers,
        answer_weights=answer_weights,
    )


def part_filter_6(part: str) -> bool:
    # E.g. if your dataset contains jpeg, txt and json, but you won't use json,
    # remove it from the list, such that it is not decoded. If you need all, keep as is
    return part in ("json", "jpg", "png")


# Loader for: /lustre/fsw/portfolios/llmservice/projects/llmservice_nlp_fm/datasets/nvlm/wdai/data/plotqa/processed
# This file was automatically generated by `nvgpt4 data prepare`.


def sample_loader_7(raw: dict) -> dict:  # Note: Images are already decoded to tensors
    j = raw["json"]

    return dict(
        __key__=raw["__key__"],
        image=raw["jpg"],  # expected type: torch.Tensor
        context=j["question_string"],  # expected type: str
        answers=j["answer"],  # expected type: typing.Union[typing.List[str], NoneType], default: None
        answer_weights=None,  # expected type: typing.Union[torch.Tensor, NoneType], default: None
    )


def part_filter_7(part: str) -> bool:
    # E.g. if your dataset contains jpeg, txt and json, but you won't use json,
    # remove it from the list, such that it is not decoded. If you need all, keep as is
    return part in ("jpg", "json")


# Loader for: /lustre/fsw/portfolios/llmservice/projects/llmservice_nlp_fm/datasets/nvlm/wdai/data/clevr-math/processed
# This file was automatically generated by `nvgpt4 data prepare`.


def sample_loader_8(raw: dict) -> dict:  # Note: Images are already decoded to tensors
    j = raw["json"]

    return dict(
        __key__=raw["__key__"],
        image=raw["jpg"],  # expected type: torch.Tensor
        context=j["question"],  # expected type: str
        answers=str(j["answer"]),  # expected type: typing.Optional[typing.List[str]], default: None
        answer_weights=None,  # expected type: typing.Optional[torch.Tensor], default: None
    )


def part_filter_8(part: str) -> bool:
    # E.g. if your dataset contains jpeg, txt and json, but you won't use json,
    # remove it from the list, such that it is not decoded. If you need all, keep as is
    return part in ("jpg", "json")


# Loader for: /lustre/fsw/portfolios/llmservice/projects/llmservice_nlp_fm/datasets/nvlm/wdai/data/MMC-Instruction/processed
# This file was automatically generated by `nvgpt4 data prepare`.


def sample_loader_9(raw: dict) -> dict:  # Note: Images are already decoded to tensors
    j = raw["json"]

    return dict(
        __key__=raw["__key__"],
        image=raw["jpg"],  # expected type: torch.Tensor
        context=j["question"].strip(),  # expected type: str
        answers=j["gt_answer"].strip(),  # expected type: typing.Union[typing.List[str], NoneType], default: None
        answer_weights=None,  # expected type: typing.Union[torch.Tensor, NoneType], default: None
    )


def part_filter_9(part: str) -> bool:
    # E.g. if your dataset contains jpeg, txt and json, but you won't use json,
    # remove it from the list, such that it is not decoded. If you need all, keep as is
    return part in ("json", "jpg")


# Loader for: /lustre/fsw/portfolios/llmservice/projects/llmservice_nlp_fm/datasets/nvlm/wdai/data/ocrvqa/processed
# This file was automatically generated by `nvgpt4 data prepare`.


def sample_loader_10(raw: dict) -> dict:  # Note: Images are already decoded to tensors
    j = raw["json"]
    return dict(
        image=raw["jpg"],  # expected type: torch.Tensor
        context=j["question"],  # expected type: str
        answers=j["answer"],  # expected type: typing.Optional[typing.List[str]], default: None
        answer_weights=None,  # expected type: typing.Optional[torch.Tensor], default: None
    )


def part_filter_10(part: str) -> bool:
    # E.g. if your dataset contains jpeg, txt and json, but you won't use json,
    # remove it from the list, such that it is not decoded. If you need all, keep as is
    return part in ("json", "jpg")


# Loader for: /lustre/fsw/portfolios/llmservice/projects/llmservice_nlp_fm/datasets/nvlm/wdai/data/dude/processed
# This file was automatically generated by `nvgpt4 data prepare`.


def sample_loader_11(raw: dict) -> dict:  # Note: Images are already decoded to tensors
    j = raw["json"]

    return dict(
        __key__=raw["__key__"],
        image=raw["jpg"],
        context=j["question"],
        answers=j["answer"],
        answer_weights=None,
    )


def part_filter_11(part: str) -> bool:
    # E.g. if your dataset contains jpeg, txt and json, but you won't use json,
    # remove it from the list, such that it is not decoded. If you need all, keep as is
    return part in ("jpg", "json")


# Loader for: /lustre/fsw/portfolios/llmservice/projects/llmservice_nlp_fm/datasets/nvlm/wdai/data/VisualMRC/processed
# This file was automatically generated by `nvgpt4 data prepare`.


def sample_loader_12(raw: dict) -> dict:  # Note: Images are already decoded to tensors
    j = raw["json"]
    return dict(
        __key__=raw["__key__"],
        image=raw["jpg"],  # expected type: torch.Tensor
        context=j["question"],  # expected type: str
        answers=j["answer"],  # expected type: typing.Optional[typing.List[str]], default: None
        answer_weights=None,  # expected type: typing.Optional[torch.Tensor], default: None
    )


def part_filter_12(part: str) -> bool:
    # E.g. if your dataset contains jpeg, txt and json, but you won't use json,
    # remove it from the list, such that it is not decoded. If you need all, keep as is
    return part in ("jpg", "json")


# Loader for: /lustre/fsw/portfolios/llmservice/projects/llmservice_nlp_fm/datasets/nvlm/wdai/data/mcvqa_collection_scienceqa_ai2d_geoqaplus_geometry3k_tqa
# This file was automatically generated by `nvgpt4 data prepare`.


def sample_loader_13(raw: dict) -> dict:  # Note: Images are already decoded to tensors
    json_item = raw["json"]
    key = raw["__key__"]

    if "geoqa_plus" in key or "tqa" in key:
        return dict(
            __key__=raw["__key__"],
            image=raw["jpg"],
            context=json_item["question"],
            choices=json_item["choices"],
            correct_choice_idx=json_item["correct_answer_index"],
        )
    elif "geometry3k" in key:
        return dict(
            __key__=raw["__key__"],
            image=raw["jpg"],
            context=json_item["question"],
            choices=json_item["choices"],
            correct_choice_idx=ord(json_item["answer"].lower()) - 97,
        )
    else:  # science_qa, ai2d
        image_key = "png" if "png" in raw else "jpg"
        if image_key not in raw:
            log.warning(f"Image key {image_key} not found in with raw keys: {raw.keys()}")
        return dict(
            __key__=raw["__key__"],  # science_qa_sample_{idx}
            image=raw[image_key],  # expected type: torch.Tensor
            context=json_item["question"],  # expected type: str
            choices=json_item["choices"],  # expected type: typing.Union[typing.List[str], NoneType], default: None
            correct_choice_idx=json_item["correct_choice_index"],
        )


def part_filter_13(part: str) -> bool:
    # E.g. if your dataset contains jpeg, txt and json, but you won't use json,
    # remove it from the list, such that it is not decoded. If you need all, keep as is
    return part in ("json", "png", "jpg")


# Loader for: /lustre/fsw/portfolios/llmservice/projects/llmservice_nlp_fm/datasets/nvlm/wdai/data/arxiv_qa/processed
# This file was automatically generated by `nvgpt4 data prepare`.


def sample_loader_14(raw: dict) -> dict:  # Note: Images are already decoded to tensors
    json_item = raw["json"]

    return dict(
        __key__=raw["__key__"],  # arxiv_qa_sample_{idx}
        image=raw["jpg"],  # expected type: torch.Tensor
        context=json_item["question"],  # expected type: str
        choices=json_item["options"],  # expected type: typing.Union[typing.List[str], NoneType], default: None
        correct_choice_idx=json_item["correct_choice_index"],
    )


def part_filter_14(part: str) -> bool:
    # E.g. if your dataset contains jpeg, txt and json, but you won't use json,
    # remove it from the list, such that it is not decoded. If you need all, keep as is
    return part in ("jpg", "json")


# Loader for: /lustre/fsw/portfolios/llmservice/projects/llmservice_nlp_fm/datasets/nvlm/wdai/data/tabmwp/processed
# This file was automatically generated by `nvgpt4 data prepare`.


def sample_loader_15(raw: dict) -> dict:  # Note: Images are already decoded to tensors
    json_item = raw["json"]

    if json_item["question_type"] == "multi_choice":
        correct_choice_idx = json_item["choices"].index(json_item["answer"])
        return dict(
            __key__=raw["__key__"],
            image=raw["jpg"],
            context=json_item["question"],
            choices=json_item["choices"],
            correct_choice_idx=correct_choice_idx,
        )
    else:
        # A temporary hack for non multi-choice samples.
        # If correct_choice_idx=-1, we should route it to the VQAWebdataset dataloading method.
        # (74.7% free-text questions, 25.3% multi-choice questions)
        return dict(
            __key__=raw["__key__"],
            image=raw["jpg"],
            context=json_item["question"],
            choices=[json_item["answer"]],
            correct_choice_idx=-1,
        )


def part_filter_15(part: str) -> bool:
    # E.g. if your dataset contains jpeg, txt and json, but you won't use json,
    # remove it from the list, such that it is not decoded. If you need all, keep as is
    return part in ("jpg", "json")


# Loader for: /lustre/fsw/portfolios/llmservice/projects/llmservice_nlp_fm/datasets/nvlm/wdai/data/ocr_vqa_aug/processed/
# This file was automatically generated by `nvgpt4 data prepare`.


def sample_loader_16(raw: dict) -> dict:  # Note: Images are already decoded to tensors
    j = raw["json"]

    return dict(
        __key__="llava-{}".format(raw["__key__"]), images=[raw["jpg"]], texts=j["conversations"], similarity_matrix=None
    )


def part_filter_16(part: str) -> bool:
    # E.g. if your dataset contains jpeg, txt and json, but you won't use json,
    # remove it from the list, such that it is not decoded. If you need all, keep as is
    return part in ("jpg", "json")


# Loader for: /lustre/fsw/portfolios/llmservice/projects/llmservice_nlp_fm/datasets/nvlm/wdai/data/dvqa_full/processed
# This file was automatically generated by `nvgpt4 data prepare`.


def sample_loader_17(raw: dict) -> dict:  # Note: Images are already decoded to tensors
    json_item = raw["json"]
    images = [raw["jpg"]]

    return dict(
        __key__="llava-{}".format(raw["__key__"]),
        images=images,
        texts=json_item["conversations"],
        similarity_matrix=None,
    )


def part_filter_17(part: str) -> bool:
    # E.g. if your dataset contains jpeg, txt and json, but you won't use json,
    # remove it from the list, such that it is not decoded. If you need all, keep as is
    return part in ("json", "jpg")


# Loader for: /lustre/fsw/portfolios/llmservice/projects/llmservice_nlp_fm/datasets/nvlm/wdai/data/LLaVA-v1.5_shuffle/no_refcoco_vg_ocrvqa
# This file was automatically generated by `nvgpt4 data prepare`.


def sample_loader_18(raw: dict) -> dict:  # Note: Images are already decoded to tensors
    json_item = raw["json"]
    images = [raw["jpg"]]

    return dict(
        __key__="llava-{}".format(raw["__key__"]),
        images=images,
        texts=json_item["conversations"],
        similarity_matrix=None,
    )


def part_filter_18(part: str) -> bool:
    # E.g. if your dataset contains jpeg, txt and json, but you won't use json,
    # remove it from the list, such that it is not decoded. If you need all, keep as is
    return part in ("json", "jpg")


# Loader for: /lustre/fsw/portfolios/llmservice/projects/llmservice_nlp_fm/datasets/vqa/more_data/infographics_vqa/processed/train/
# This file was automatically generated by `nvgpt4 data prepare`.


def sample_loader_19(raw: dict) -> dict:  # Note: Images are already decoded to tensors
    json_item = raw["json"]
    images = [raw["jpg"]]

    return dict(
        __key__="llava-{}".format(raw["__key__"]),
        images=images,  # expected type: torch.Tensor
        texts=json_item["conversations"],
        similarity_matrix=None,
    )


def part_filter_19(part: str) -> bool:
    return part in ("jpg", "json")


# Loader for: /lustre/fsw/portfolios/llmservice/projects/llmservice_nlp_fm/datasets/nvlm/wdai/data/sharegpt4o/processed
# This file was automatically generated by `nvgpt4 data prepare`.


def sample_loader_20(raw: dict) -> dict:  # Note: Images are already decoded to tensors
    j = raw["json"]

    return dict(
        __key__="llava-{}".format(raw["__key__"]), images=[raw["jpg"]], texts=j["conversations"], similarity_matrix=None
    )


def part_filter_20(part: str) -> bool:
    # E.g. if your dataset contains jpeg, txt and json, but you won't use json,
    # remove it from the list, such that it is not decoded. If you need all, keep as is
    return part in ("jpg", "json")


# Loader for: /lustre/fsw/portfolios/llmservice/projects/llmservice_nlp_fm/datasets/nvlm/wdai/data/sparse_ocr_data/merged
# This file was automatically generated by `nvgpt4 data prepare`.


def sample_loader_21(raw: dict) -> dict:  # Note: Images are already decoded to tensors
    j = raw["json"]

    return dict(
        __key__="llava-{}".format(raw["__key__"]), images=[raw["png"]], texts=j["conversations"], similarity_matrix=None
    )


def part_filter_21(part: str) -> bool:
    # E.g. if your dataset contains jpeg, txt and json, but you won't use json,
    # remove it from the list, such that it is not decoded. If you need all, keep as is
    return part in ("json", "png")


# Loader for: /lustre/fsw/portfolios/llmservice/projects/llmservice_nlp_fm/datasets/nvlm/nayeonl/data/blendv4/MetaMathQA/processed/train_text_image
# This file was automatically generated by `nvgpt4 data prepare`.


def sample_loader_22(raw: dict) -> dict:  # Note: Images are already decoded to tensors
    json_item = raw["json"]
    images = [raw["jpg"]]

    return dict(
        __key__="llava-{}".format(raw["__key__"]),
        images=images,  # expected type: torch.Tensor
        texts=json_item["conversations"],
        similarity_matrix=None,
    )


def part_filter_22(part: str) -> bool:
    return part in ("jpg", "json")


# Loader for: /lustre/fsw/portfolios/llmservice/projects/llmservice_nlp_fm/datasets/nvlm/nayeonl/data/blendv4/gsm8k/processed/train_text_image
# This file was automatically generated by `nvgpt4 data prepare`.


def sample_loader_23(raw: dict) -> dict:  # Note: Images are already decoded to tensors
    json_item = raw["json"]
    images = [raw["jpg"]]

    return dict(
        __key__="llava-{}".format(raw["__key__"]),
        images=images,  # expected type: torch.Tensor
        texts=json_item["conversations"],
        similarity_matrix=None,
    )


def part_filter_23(part: str) -> bool:
    return part in ("jpg", "json")


# Loader for: /lustre/fsw/portfolios/llmservice/projects/llmservice_nlp_fm/datasets/nvlm/wdai/data/docmatix/processed
# This file was automatically generated by `nvgpt4 data prepare`.


def sample_loader_24(raw: dict) -> dict:  # Note: Images are already decoded to tensors
    json_item = raw["json"]
    images = [raw["jpg"]]

    return dict(
        __key__="llava-{}".format(raw["__key__"]),
        images=images,
        texts=json_item["conversations"],
        similarity_matrix=None,
    )


def part_filter_24(part: str) -> bool:
    # E.g. if your dataset contains jpeg, txt and json, but you won't use json,
    # remove it from the list, such that it is not decoded. If you need all, keep as is
    return part in ("json", "jpg")


# Loader for: /lustre/fsw/portfolios/llmservice/projects/llmservice_nlp_fm/datasets/nvlm/wdai/data/bentham_hw_squad/processed
# This file was automatically generated by `nvgpt4 data prepare`.


def sample_loader_25(raw: dict) -> dict:  # Note: Images are already decoded to tensors
    j = raw["json"]

    return dict(
        __key__="llava-{}".format(raw["__key__"]), images=[raw["jpg"]], texts=j["conversations"], similarity_matrix=None
    )


def part_filter_25(part: str) -> bool:
    # E.g. if your dataset contains jpeg, txt and json, but you won't use json,
    # remove it from the list, such that it is not decoded. If you need all, keep as is
    return part in ("json", "jpg")


# Loader for: /lustre/fsw/portfolios/llmservice/projects/llmservice_nlp_fm/datasets/nvlm/wdai/data/WikiTableQA/processed
# This file was automatically generated by `nvgpt4 data prepare`.


def sample_loader_26(raw: dict) -> dict:  # Note: Images are already decoded to tensors
    j = raw["json"]

    return dict(
        __key__="llava-{}".format(raw["__key__"]), images=[raw["jpg"]], texts=j["conversations"], similarity_matrix=None
    )


def part_filter_26(part: str) -> bool:
    # E.g. if your dataset contains jpeg, txt and json, but you won't use json,
    # remove it from the list, such that it is not decoded. If you need all, keep as is
    return part in ("jpg", "json")


# Loader for: /lustre/fsw/portfolios/llmservice/projects/llmservice_nlp_fm/datasets/nvlm/wdai/data/figureqa/processed
# This file was automatically generated by `nvgpt4 data prepare`.


def sample_loader_27(raw: dict) -> dict:  # Note: Images are already decoded to tensors
    json_item = raw["json"]
    images = [raw["jpg"]]

    return dict(
        __key__="llava-{}".format(raw["__key__"]),
        images=images,
        texts=json_item["conversations"],
        similarity_matrix=None,
    )


def part_filter_27(part: str) -> bool:
    # E.g. if your dataset contains jpeg, txt and json, but you won't use json,
    # remove it from the list, such that it is not decoded. If you need all, keep as is
    return part in ("json", "jpg")


# Loader for: /lustre/fsw/portfolios/llmservice/projects/llmservice_nlp_fm/datasets/nvlm/wdai/data/llava-onevision/ai2d_combined_processed
# This file was automatically generated by `nvgpt4 data prepare`.


def sample_loader_28(raw: dict) -> dict:  # Note: Images are already decoded to tensors
    json_item = raw["json"]
    images = [raw["jpg"]]

    return dict(
        __key__="llava-{}".format(raw["__key__"]),
        images=images,
        texts=json_item["conversations"],
        similarity_matrix=None,
    )


def part_filter_28(part: str) -> bool:
    # E.g. if your dataset contains jpeg, txt and json, but you won't use json,
    # remove it from the list, such that it is not decoded. If you need all, keep as is
    return part in ("jpg", "json")


# Loader for: /lustre/fsw/portfolios/llmservice/projects/llmservice_nlp_fm/datasets/nvlm/wdai/data/llava-onevision/math_combined_processed
# This file was automatically generated by `nvgpt4 data prepare`.


def sample_loader_29(raw: dict) -> dict:  # Note: Images are already decoded to tensors
    json_item = raw["json"]
    images = [raw["jpg"]]

    return dict(
        __key__="llava-{}".format(raw["__key__"]),
        images=images,
        texts=json_item["conversations"],
        similarity_matrix=None,
    )


def part_filter_29(part: str) -> bool:
    # E.g. if your dataset contains jpeg, txt and json, but you won't use json,
    # remove it from the list, such that it is not decoded. If you need all, keep as is
    return part in ("json", "jpg")


# Loader for: /lustre/fsw/portfolios/llmservice/projects/llmservice_nlp_fm/datasets/nvlm/wdai/data/llava-onevision/robut_combined_processed
# This file was automatically generated by `nvgpt4 data prepare`.


def sample_loader_30(raw: dict) -> dict:  # Note: Images are already decoded to tensors
    json_item = raw["json"]
    images = [raw["jpg"]]

    return dict(
        __key__="llava-{}".format(raw["__key__"]),
        images=images,
        texts=json_item["conversations"],
        similarity_matrix=None,
    )


def part_filter_30(part: str) -> bool:
    # E.g. if your dataset contains jpeg, txt and json, but you won't use json,
    # remove it from the list, such that it is not decoded. If you need all, keep as is
    return part in ("json", "jpg")


# Loader for: /lustre/fsw/portfolios/llmservice/projects/llmservice_nlp_fm/datasets/nvlm/wdai/data/llava-onevision/llavar_20k_processed
# This file was automatically generated by `nvgpt4 data prepare`.


def sample_loader_31(raw: dict) -> dict:  # Note: Images are already decoded to tensors
    json_item = raw["json"]
    images = [raw["jpg"]]

    return dict(
        __key__="llava-{}".format(raw["__key__"]),
        images=images,
        texts=json_item["conversations"],
        similarity_matrix=None,
    )


def part_filter_31(part: str) -> bool:
    # E.g. if your dataset contains jpeg, txt and json, but you won't use json,
    # remove it from the list, such that it is not decoded. If you need all, keep as is
    return part in ("jpg", "json")


# Loader for: /lustre/fsw/portfolios/llmservice/projects/llmservice_nlp_fm/datasets/nvlm/wdai/data/llava-onevision/tallyqa_processed
# This file was automatically generated by `nvgpt4 data prepare`.


def sample_loader_32(raw: dict) -> dict:  # Note: Images are already decoded to tensors
    json_item = raw["json"]
    images = [raw["jpg"]]

    return dict(
        __key__="llava-{}".format(raw["__key__"]),
        images=images,
        texts=json_item["conversations"],
        similarity_matrix=None,
    )


def part_filter_32(part: str) -> bool:
    # E.g. if your dataset contains jpeg, txt and json, but you won't use json,
    # remove it from the list, such that it is not decoded. If you need all, keep as is
    return part in ("json", "jpg")


# Loader for: /lustre/fsw/portfolios/llmservice/projects/llmservice_nlp_fm/datasets/nvlm/wdai/data/llava-onevision/ureader_ie_processed
# This file was automatically generated by `nvgpt4 data prepare`.


def sample_loader_33(raw: dict) -> dict:  # Note: Images are already decoded to tensors
    json_item = raw["json"]
    images = [raw["jpg"]]

    return dict(
        __key__="llava-{}".format(raw["__key__"]),
        images=images,
        texts=json_item["conversations"],
        similarity_matrix=None,
    )


def part_filter_33(part: str) -> bool:
    # E.g. if your dataset contains jpeg, txt and json, but you won't use json,
    # remove it from the list, such that it is not decoded. If you need all, keep as is
    return part in ("json", "jpg")


# Loader for: /lustre/fsw/portfolios/llmservice/projects/llmservice_nlp_fm/datasets/nvlm/wdai/data/llava-onevision/visual7w_processed
# This file was automatically generated by `nvgpt4 data prepare`.


def sample_loader_34(raw: dict) -> dict:  # Note: Images are already decoded to tensors
    json_item = raw["json"]
    images = [raw["jpg"]]

    return dict(
        __key__="llava-{}".format(raw["__key__"]),
        images=images,
        texts=json_item["conversations"],
        similarity_matrix=None,
    )


def part_filter_34(part: str) -> bool:
    # E.g. if your dataset contains jpeg, txt and json, but you won't use json,
    # remove it from the list, such that it is not decoded. If you need all, keep as is
    return part in ("json", "jpg")


# Loader for: /lustre/fsw/portfolios/llmservice/projects/llmservice_nlp_fm/datasets/nvlm/wdai/data/llava-onevision/mavis_math_rule_geo_processed
# This file was automatically generated by `nvgpt4 data prepare`.


def sample_loader_35(raw: dict) -> dict:  # Note: Images are already decoded to tensors
    json_item = raw["json"]
    images = [raw["jpg"]]

    return dict(
        __key__="llava-{}".format(raw["__key__"]),
        images=images,
        texts=json_item["conversations"],
        similarity_matrix=None,
    )


def part_filter_35(part: str) -> bool:
    # E.g. if your dataset contains jpeg, txt and json, but you won't use json,
    # remove it from the list, such that it is not decoded. If you need all, keep as is
    return part in ("jpg", "json")


# Loader for: /lustre/fsw/portfolios/llmservice/projects/llmservice_nlp_fm/datasets/nvlm/wdai/data/llava-onevision/ureader_kg_processed
# This file was automatically generated by `nvgpt4 data prepare`.


def sample_loader_36(raw: dict) -> dict:  # Note: Images are already decoded to tensors
    json_item = raw["json"]
    images = [raw["jpg"]]

    return dict(
        __key__="llava-{}".format(raw["__key__"]),
        images=images,
        texts=json_item["conversations"],
        similarity_matrix=None,
    )


def part_filter_36(part: str) -> bool:
    # E.g. if your dataset contains jpeg, txt and json, but you won't use json,
    # remove it from the list, such that it is not decoded. If you need all, keep as is
    return part in ("jpg", "json")


# Loader for: /lustre/fsw/portfolios/llmservice/projects/llmservice_nlp_fm/datasets/nvlm/wdai/data/llava-onevision/ureader_qa_processed
# This file was automatically generated by `nvgpt4 data prepare`.


def sample_loader_37(raw: dict) -> dict:  # Note: Images are already decoded to tensors
    json_item = raw["json"]
    images = [raw["jpg"]]

    return dict(
        __key__="llava-{}".format(raw["__key__"]),
        images=images,
        texts=json_item["conversations"],
        similarity_matrix=None,
    )


def part_filter_37(part: str) -> bool:
    # E.g. if your dataset contains jpeg, txt and json, but you won't use json,
    # remove it from the list, such that it is not decoded. If you need all, keep as is
    return part in ("json", "jpg")


# Loader for: /lustre/fsw/portfolios/llmservice/projects/llmservice_nlp_fm/datasets/nvlm/wdai/data/ocr_multi_collection_cocotext_textocr_ReCTs
# This file was automatically generated by `nvgpt4 data prepare`.


def sample_loader_38(raw: dict) -> dict:
    j = raw["json"]

    if "ReCTs" in raw["__key__"]:
        return dict(
            __key__=raw["__key__"],
            image=raw["jpg"],
            text="",
            words_boxes=j["quads_1k_normalized"],
            words_text=j["texts"],
        )
    else:  # coco-text-multi, textocr-multi
        return dict(
            __key__=raw["__key__"],
            image=raw["jpg"],
            text="",
            words_boxes=j["bboxes_1k_normalized"],
            words_text=j["texts"],
        )


def part_filter_38(part: str) -> bool:
    # E.g. if your dataset contains jpeg, txt and json, but you won't use json,
    # remove it from the list, such that it is not decoded. If you need all, keep as is
    return part in ("jpg", "json")


# Loader for: /lustre/fsw/portfolios/llmservice/projects/llmservice_nlp_fm/datasets/nvlm/wdai/data/pdfa-eng-wds/processed_word_len_500
# This file was automatically generated by `nvgpt4 data prepare`.


def sample_loader_39(raw: dict) -> dict:  # Note: Images are already decoded to tensors
    j = raw["json"]
    return dict(
        image=raw["jpg"],  # expected type: torch.Tensor
        text=" ".join(j["lines"]["text"]),  # expected type: str
    )


def part_filter_39(part: str) -> bool:
    # E.g. if your dataset contains jpeg, txt and json, but you won't use json,
    # remove it from the list, such that it is not decoded. If you need all, keep as is
    return part in ("jpg", "json")


# Loader for: /lustre/fsw/portfolios/llmservice/projects/llmservice_nlp_fm/datasets/nvlm/wdai/data/llava-onevision/super_clevr_processed
# This file was automatically generated by `nvgpt4 data prepare`.


def sample_loader_40(raw: dict) -> dict:  # Note: Images are already decoded to tensors
    json_item = raw["json"]
    images = [raw["jpg"]]

    return dict(
        __key__="llava-{}".format(raw["__key__"]),
        images=images,
        texts=json_item["conversations"],
        similarity_matrix=None,
    )


def part_filter_40(part: str) -> bool:
    # E.g. if your dataset contains jpeg, txt and json, but you won't use json,
    # remove it from the list, such that it is not decoded. If you need all, keep as is
    return part in ("json", "jpg")


# Loader for: /lustre/fsw/portfolios/llmservice/projects/llmservice_nlp_fm/datasets/nvlm/wdai/data/llava-onevision/icon_qa_processed
# This file was automatically generated by `nvgpt4 data prepare`.


def sample_loader_41(raw: dict) -> dict:  # Note: Images are already decoded to tensors
    json_item = raw["json"]
    images = [raw["jpg"]]

    return dict(
        __key__="llava-{}".format(raw["__key__"]),
        images=images,
        texts=json_item["conversations"],
        similarity_matrix=None,
    )


def part_filter_41(part: str) -> bool:
    # E.g. if your dataset contains jpeg, txt and json, but you won't use json,
    # remove it from the list, such that it is not decoded. If you need all, keep as is
    return part in ("jpg", "json")


# Loader for: /lustre/fsw/portfolios/llmservice/projects/llmservice_nlp_fm/datasets/nvlm/wdai/data/augmentations/chartqa_aug
# This file was automatically generated by `nvgpt4 data prepare`.


def sample_loader_42(raw: dict) -> dict:  # Note: Images are already decoded to tensors
    json_item = raw["json"]

    img = Image.open(io.BytesIO(raw["img"]))
    images = [img]

    return dict(
        __key__="llava-{}".format(raw["__key__"]),
        images=images,
        texts=json_item["conversations"],
        similarity_matrix=None,
    )


def part_filter_42(part: str) -> bool:
    # E.g. if your dataset contains jpeg, txt and json, but you won't use json,
    # remove it from the list, such that it is not decoded. If you need all, keep as is
    return part in ("img", "json")


# Loader for: /lustre/fsw/portfolios/llmservice/projects/llmservice_nlp_fm/datasets/nvlm/wdai/data/augmentations/gpt_chartqa
# This file was automatically generated by `nvgpt4 data prepare`.


def sample_loader_43(raw: dict) -> dict:  # Note: Images are already decoded to tensors
    json_item = raw["json"]

    img = Image.open(io.BytesIO(raw["img"]))
    images = [img]

    return dict(
        __key__="llava-{}".format(raw["__key__"]),
        images=images,
        texts=json_item["conversations"],
        similarity_matrix=None,
    )


def part_filter_43(part: str) -> bool:
    # E.g. if your dataset contains jpeg, txt and json, but you won't use json,
    # remove it from the list, such that it is not decoded. If you need all, keep as is
    return part in ("img", "json")


# Loader for: /lustre/fsw/portfolios/llmservice/projects/llmservice_nlp_fm/datasets/nvlm/wdai/data/augmentations/gpt_docvqa
# This file was automatically generated by `nvgpt4 data prepare`.


def sample_loader_44(raw: dict) -> dict:  # Note: Images are already decoded to tensors
    json_item = raw["json"]

    img = Image.open(io.BytesIO(raw["img"]))
    images = [img]

    return dict(
        __key__="llava-{}".format(raw["__key__"]),
        images=images,
        texts=json_item["conversations"],
        similarity_matrix=None,
    )


def part_filter_44(part: str) -> bool:
    # E.g. if your dataset contains jpeg, txt and json, but you won't use json,
    # remove it from the list, such that it is not decoded. If you need all, keep as is
    return part in ("img", "json")


# Loader for: /lustre/fsw/portfolios/llmservice/projects/llmservice_nlp_fm/datasets/nvlm/wdai/data/augmentations/docvqa_text
# This file was automatically generated by `nvgpt4 data prepare`.


def sample_loader_45(raw: dict) -> dict:  # Note: Images are already decoded to tensors
    json_item = raw["json"]

    img = Image.open(io.BytesIO(raw["img"]))
    images = [img]

    return dict(
        __key__="llava-{}".format(raw["__key__"]),
        images=images,
        texts=json_item["conversations"],
        similarity_matrix=None,
    )


def part_filter_45(part: str) -> bool:
    # E.g. if your dataset contains jpeg, txt and json, but you won't use json,
    # remove it from the list, such that it is not decoded. If you need all, keep as is
    return part in ("img", "json")


# Loader for: /lustre/fsw/portfolios/llmservice/projects/llmservice_nlp_fm/datasets/nvlm/wdai/data/augmentations/textvqa_text
# This file was automatically generated by `nvgpt4 data prepare`.


def sample_loader_46(raw: dict) -> dict:  # Note: Images are already decoded to tensors
    json_item = raw["json"]

    img = Image.open(io.BytesIO(raw["img"]))
    images = [img]

    return dict(
        __key__="llava-{}".format(raw["__key__"]),
        images=images,
        texts=json_item["conversations"],
        similarity_matrix=None,
    )


def part_filter_46(part: str) -> bool:
    # E.g. if your dataset contains jpeg, txt and json, but you won't use json,
    # remove it from the list, such that it is not decoded. If you need all, keep as is
    return part in ("img", "json")


# Loader for: /lustre/fsw/portfolios/llmservice/projects/llmservice_nlp_fm/datasets/nvlm/wdai/data/augmentations/i2s-musicsheet
# This file was automatically generated by `nvgpt4 data prepare`.


def sample_loader_47(raw: dict) -> dict:  # Note: Images are already decoded to tensors
    json_item = raw["json"]

    img = Image.open(io.BytesIO(raw["img"]))
    images = [img]

    return dict(
        __key__="llava-{}".format(raw["__key__"]),
        images=images,
        texts=json_item["conversations"],
        similarity_matrix=None,
    )


def part_filter_47(part: str) -> bool:
    # E.g. if your dataset contains jpeg, txt and json, but you won't use json,
    # remove it from the list, such that it is not decoded. If you need all, keep as is
    return part in ("img", "json")


# Loader for: /lustre/fsw/portfolios/llmservice/projects/llmservice_nlp_fm/datasets/nvlm/wdai/data/augmentations/music
# This file was automatically generated by `nvgpt4 data prepare`.


def sample_loader_48(raw: dict) -> dict:  # Note: Images are already decoded to tensors
    json_item = raw["json"]

    img = Image.open(io.BytesIO(raw["img"]))
    images = [img]

    return dict(
        __key__="llava-{}".format(raw["__key__"]),
        images=images,
        texts=json_item["conversations"],
        similarity_matrix=None,
    )


def part_filter_48(part: str) -> bool:
    # E.g. if your dataset contains jpeg, txt and json, but you won't use json,
    # remove it from the list, such that it is not decoded. If you need all, keep as is
    return part in ("img", "json")


# Loader for: /lustre/fsw/portfolios/llmservice/projects/llmservice_nlp_fm/datasets/nvlm/wdai/data/augmentations/invoice
# This file was automatically generated by `nvgpt4 data prepare`.


def sample_loader_49(raw: dict) -> dict:  # Note: Images are already decoded to tensors
    json_item = raw["json"]

    img = Image.open(io.BytesIO(raw["img"]))
    images = [img]

    return dict(
        __key__="llava-{}".format(raw["__key__"]),
        images=images,
        texts=json_item["conversations"],
        similarity_matrix=None,
    )


def part_filter_49(part: str) -> bool:
    # E.g. if your dataset contains jpeg, txt and json, but you won't use json,
    # remove it from the list, such that it is not decoded. If you need all, keep as is
    return part in ("img", "json")


# Loader for: /lustre/fsw/portfolios/llmservice/projects/llmservice_nlp_fm/datasets/nvlm/wdai/data/augmentations/k12
# This file was automatically generated by `nvgpt4 data prepare`.


def sample_loader_50(raw: dict) -> dict:  # Note: Images are already decoded to tensors
    json_item = raw["json"]

    img = Image.open(io.BytesIO(raw["img"]))
    images = [img]

    return dict(
        __key__="llava-{}".format(raw["__key__"]),
        images=images,
        texts=json_item["conversations"],
        similarity_matrix=None,
    )


def part_filter_50(part: str) -> bool:
    # E.g. if your dataset contains jpeg, txt and json, but you won't use json,
    # remove it from the list, such that it is not decoded. If you need all, keep as is
    return part in ("img", "json")


# Loader for: /lustre/fsw/portfolios/llmservice/projects/llmservice_nlp_fm/datasets/nvlm/wdai/data/augmentations/MTVQA
# This file was automatically generated by `nvgpt4 data prepare`.


def sample_loader_51(raw: dict) -> dict:  # Note: Images are already decoded to tensors
    json_item = raw["json"]
    for i, turn in enumerate(json_item["conversations"]):
        if i > 0 and turn["from"] == "human" and "<image>" in turn["value"]:
            turn["value"] = turn["value"].replace("<image>\n", "")

    img = Image.open(io.BytesIO(raw["img"]))
    images = [img]

    return dict(
        __key__="llava-{}".format(raw["__key__"]),
        images=images,
        texts=json_item["conversations"],
        similarity_matrix=None,
    )


def part_filter_51(part: str) -> bool:
    # E.g. if your dataset contains jpeg, txt and json, but you won't use json,
    # remove it from the list, such that it is not decoded. If you need all, keep as is
    return part in ("img", "json")


# Loader for: /lustre/fsw/portfolios/llmservice/projects/llmservice_nlp_fm/datasets/nvlm/wdai/data/augmentations/VisualWebInstruct
# This file was automatically generated by `nvgpt4 data prepare`.


def sample_loader_52(raw: dict) -> dict:  # Note: Images are already decoded to tensors
    json_item = raw["json"]

    img = Image.open(io.BytesIO(raw["img"]))
    images = [img]

    return dict(
        __key__="llava-{}".format(raw["__key__"]),
        images=images,
        texts=json_item["conversations"],
        similarity_matrix=None,
    )


def part_filter_52(part: str) -> bool:
    # E.g. if your dataset contains jpeg, txt and json, but you won't use json,
    # remove it from the list, such that it is not decoded. If you need all, keep as is
    return part in ("img", "json")


# Loader for: /lustre/fsw/portfolios/llmservice/projects/llmservice_nlp_fm/datasets/nvlm/wdai/data/augmentations/financeqa
# This file was automatically generated by `nvgpt4 data prepare`.


def sample_loader_53(raw: dict) -> dict:  # Note: Images are already decoded to tensors
    json_item = raw["json"]
    # for i, turn in enumerate(json_item['conversations']):
    #     if i > 0 and turn['from'] == 'human' and '<image>' in turn['value']:
    #         turn['value'] = turn['value'].replace("<image>\n", "")

    img = Image.open(io.BytesIO(raw["img"]))
    images = [img]

    return dict(
        __key__="llava-{}".format(raw["__key__"]),
        images=images,
        texts=json_item["conversations"],
        similarity_matrix=None,
    )


def part_filter_53(part: str) -> bool:
    # E.g. if your dataset contains jpeg, txt and json, but you won't use json,
    # remove it from the list, such that it is not decoded. If you need all, keep as is
    return part in ("img", "json")


# Loader for: /lustre/fsw/portfolios/llmservice/projects/llmservice_nlp_fm/datasets/nvlm/wdai/data/augmentations/docreason
# This file was automatically generated by `nvgpt4 data prepare`.


def sample_loader_54(raw: dict) -> dict:  # Note: Images are already decoded to tensors
    json_item = raw["json"]

    img = Image.open(io.BytesIO(raw["img"]))
    images = [img]

    return dict(
        __key__="llava-{}".format(raw["__key__"]),
        images=images,
        texts=json_item["conversations"],
        similarity_matrix=None,
    )


def part_filter_54(part: str) -> bool:
    # E.g. if your dataset contains jpeg, txt and json, but you won't use json,
    # remove it from the list, such that it is not decoded. If you need all, keep as is
    return part in ("img", "json")


# Loader for: /lustre/fsw/portfolios/llmservice/projects/llmservice_nlp_fm/datasets/nvlm/wdai/data/augmentations/gpt_mtwi
# This file was automatically generated by `nvgpt4 data prepare`.


def sample_loader_55(raw: dict) -> dict:  # Note: Images are already decoded to tensors
    json_item = raw["json"]

    img = Image.open(io.BytesIO(raw["img"]))
    images = [img]

    return dict(
        __key__="llava-{}".format(raw["__key__"]),
        images=images,
        texts=json_item["conversations"],
        similarity_matrix=None,
    )


def part_filter_55(part: str) -> bool:
    # E.g. if your dataset contains jpeg, txt and json, but you won't use json,
    # remove it from the list, such that it is not decoded. If you need all, keep as is
    return part in ("img", "json")


# Loader for: /lustre/fsw/portfolios/llmservice/projects/llmservice_nlp_fm/datasets/nvlm/wdai/data/augmentations/geos_gpt
# This file was automatically generated by `nvgpt4 data prepare`.


def sample_loader_56(raw: dict) -> dict:  # Note: Images are already decoded to tensors
    json_item = raw["json"]

    img = Image.open(io.BytesIO(raw["img"]))
    images = [img]

    return dict(
        __key__="llava-{}".format(raw["__key__"]),
        images=images,
        texts=json_item["conversations"],
        similarity_matrix=None,
    )


def part_filter_56(part: str) -> bool:
    # E.g. if your dataset contains jpeg, txt and json, but you won't use json,
    # remove it from the list, such that it is not decoded. If you need all, keep as is
    return part in ("img", "json")


# Loader for: /lustre/fsw/portfolios/llmservice/projects/llmservice_nlp_fm/datasets/nvlm/wdai/data/augmentations/cauldron_vistext
# This file was automatically generated by `nvgpt4 data prepare`.


def sample_loader_57(raw: dict) -> dict:  # Note: Images are already decoded to tensors
    json_item = raw["json"]

    img = Image.open(io.BytesIO(raw["img"]))
    images = [img]

    return dict(
        __key__="llava-{}".format(raw["__key__"]),
        images=images,
        texts=json_item["conversations"],
        similarity_matrix=None,
    )


def part_filter_57(part: str) -> bool:
    # E.g. if your dataset contains jpeg, txt and json, but you won't use json,
    # remove it from the list, such that it is not decoded. If you need all, keep as is
    return part in ("img", "json")


# Loader for: /lustre/fsw/portfolios/llmservice/projects/llmservice_nlp_fm/datasets/nvlm/wdai/data/augmentations/memes
# This file was automatically generated by `nvgpt4 data prepare`.


def sample_loader_58(raw: dict) -> dict:  # Note: Images are already decoded to tensors
    json_item = raw["json"]

    img = Image.open(io.BytesIO(raw["img"]))
    images = [img]

    return dict(
        __key__="llava-{}".format(raw["__key__"]),
        images=images,
        texts=json_item["conversations"],
        similarity_matrix=None,
    )


def part_filter_58(part: str) -> bool:
    # E.g. if your dataset contains jpeg, txt and json, but you won't use json,
    # remove it from the list, such that it is not decoded. If you need all, keep as is
    return part in ("img", "json")


# Loader for: /lustre/fsw/portfolios/llmservice/projects/llmservice_nlp_fm/datasets/nvlm/wdai/data/augmentations/gpt_roadtext
# This file was automatically generated by `nvgpt4 data prepare`.


def sample_loader_59(raw: dict) -> dict:  # Note: Images are already decoded to tensors
    json_item = raw["json"]

    img = Image.open(io.BytesIO(raw["img"]))
    images = [img]

    return dict(
        __key__="llava-{}".format(raw["__key__"]),
        images=images,
        texts=json_item["conversations"],
        similarity_matrix=None,
    )


def part_filter_59(part: str) -> bool:
    # E.g. if your dataset contains jpeg, txt and json, but you won't use json,
    # remove it from the list, such that it is not decoded. If you need all, keep as is
    return part in ("img", "json")


# Loader for: /lustre/fsw/portfolios/llmservice/projects/llmservice_nlp_fm/datasets/nvlm/wdai/data/augmentations/indoor_qa
# This file was automatically generated by `nvgpt4 data prepare`.


def sample_loader_60(raw: dict) -> dict:  # Note: Images are already decoded to tensors
    json_item = raw["json"]

    img = Image.open(io.BytesIO(raw["img"]))
    images = [img]

    return dict(
        __key__="llava-{}".format(raw["__key__"]),
        images=images,
        texts=json_item["conversations"],
        similarity_matrix=None,
    )


def part_filter_60(part: str) -> bool:
    # E.g. if your dataset contains jpeg, txt and json, but you won't use json,
    # remove it from the list, such that it is not decoded. If you need all, keep as is
    return part in ("img", "json")


# Loader for: /lustre/fsw/portfolios/llmservice/projects/llmservice_nlp_fm/datasets/nvlm/wdai/data/augmentations/colpali
# This file was automatically generated by `nvgpt4 data prepare`.


def sample_loader_61(raw: dict) -> dict:  # Note: Images are already decoded to tensors
    json_item = raw["json"]

    img = Image.open(io.BytesIO(raw["img"]))
    images = [img]

    return dict(
        __key__="llava-{}".format(raw["__key__"]),
        images=images,
        texts=json_item["conversations"],
        similarity_matrix=None,
    )


def part_filter_61(part: str) -> bool:
    # E.g. if your dataset contains jpeg, txt and json, but you won't use json,
    # remove it from the list, such that it is not decoded. If you need all, keep as is
    return part in ("img", "json")


# Loader for: /lustre/fsw/portfolios/llmservice/projects/llmservice_nlp_fm/datasets/nvlm/wdai/data/augmentations/pmc_vqa
# This file was automatically generated by `nvgpt4 data prepare`.


def sample_loader_62(raw: dict) -> dict:  # Note: Images are already decoded to tensors
    json_item = raw["json"]

    img = Image.open(io.BytesIO(raw["img"]))
    images = [img]

    return dict(
        __key__="llava-{}".format(raw["__key__"]),
        images=images,
        texts=json_item["conversations"],
        similarity_matrix=None,
    )


def part_filter_62(part: str) -> bool:
    # E.g. if your dataset contains jpeg, txt and json, but you won't use json,
    # remove it from the list, such that it is not decoded. If you need all, keep as is
    return part in ("img", "json")


# Loader for: /lustre/fsw/portfolios/llmservice/projects/llmservice_nlp_fm/datasets/nvlm/wdai/data/augmentations/pathvqa
# This file was automatically generated by `nvgpt4 data prepare`.


def sample_loader_63(raw: dict) -> dict:  # Note: Images are already decoded to tensors
    json_item = raw["json"]

    img = Image.open(io.BytesIO(raw["img"]))
    images = [img]

    return dict(
        __key__="llava-{}".format(raw["__key__"]),
        images=images,
        texts=json_item["conversations"],
        similarity_matrix=None,
    )


def part_filter_63(part: str) -> bool:
    # E.g. if your dataset contains jpeg, txt and json, but you won't use json,
    # remove it from the list, such that it is not decoded. If you need all, keep as is
    return part in ("img", "json")


# Loader for: /lustre/fsw/portfolios/llmservice/projects/llmservice_nlp_fm/datasets/nvlm/wdai/data/augmentations/sciqa
# This file was automatically generated by `nvgpt4 data prepare`.


def sample_loader_64(raw: dict) -> dict:  # Note: Images are already decoded to tensors
    json_item = raw["json"]

    img = Image.open(io.BytesIO(raw["img"]))
    images = [img]

    return dict(
        __key__="llava-{}".format(raw["__key__"]),
        images=images,
        texts=json_item["conversations"],
        similarity_matrix=None,
    )


def part_filter_64(part: str) -> bool:
    # E.g. if your dataset contains jpeg, txt and json, but you won't use json,
    # remove it from the list, such that it is not decoded. If you need all, keep as is
    return part in ("img", "json")


# Loader for: /lustre/fsw/portfolios/llmservice/projects/llmservice_nlp_fm/datasets/nvlm/wdai/data/augmentations/chinese_meme
# This file was automatically generated by `nvgpt4 data prepare`.


def sample_loader_65(raw: dict) -> dict:  # Note: Images are already decoded to tensors
    json_item = raw["json"]

    img = Image.open(io.BytesIO(raw["img"]))
    images = [img]

    return dict(
        __key__="llava-{}".format(raw["__key__"]),
        images=images,
        texts=json_item["conversations"],
        similarity_matrix=None,
    )


def part_filter_65(part: str) -> bool:
    # E.g. if your dataset contains jpeg, txt and json, but you won't use json,
    # remove it from the list, such that it is not decoded. If you need all, keep as is
    return part in ("img", "json")


# Loader for: /lustre/fsw/portfolios/llmservice/projects/llmservice_nlp_fm/datasets/nvlm/wdai/data/augmentations/gpt_hiertext
# This file was automatically generated by `nvgpt4 data prepare`.


def sample_loader_66(raw: dict) -> dict:  # Note: Images are already decoded to tensors
    json_item = raw["json"]

    img = Image.open(io.BytesIO(raw["img"]))
    images = [img]

    return dict(
        __key__="llava-{}".format(raw["__key__"]),
        images=images,
        texts=json_item["conversations"],
        similarity_matrix=None,
    )


def part_filter_66(part: str) -> bool:
    # E.g. if your dataset contains jpeg, txt and json, but you won't use json,
    # remove it from the list, such that it is not decoded. If you need all, keep as is
    return part in ("img", "json")


# Loader for: /lustre/fsw/portfolios/llmservice/projects/llmservice_nlp_fm/datasets/nvlm/wdai/data/augmentations/cauldron_cocoqa
# This file was automatically generated by `nvgpt4 data prepare`.


def sample_loader_67(raw: dict) -> dict:  # Note: Images are already decoded to tensors
    json_item = raw["json"]

    img = Image.open(io.BytesIO(raw["img"]))
    images = [img]

    return dict(
        __key__="llava-{}".format(raw["__key__"]),
        images=images,
        texts=json_item["conversations"],
        similarity_matrix=None,
    )


def part_filter_67(part: str) -> bool:
    # E.g. if your dataset contains jpeg, txt and json, but you won't use json,
    # remove it from the list, such that it is not decoded. If you need all, keep as is
    return part in ("img", "json")


# Loader for: /lustre/fsw/portfolios/llmservice/projects/llmservice_nlp_fm/datasets/nvlm/wdai/data/cmm-math/processed
# This file was automatically generated by `nvgpt4 data prepare`.


def sample_loader_68(raw: dict) -> dict:  # Note: Images are already decoded to tensors
    json_item = raw["json"]
    images = [raw["jpg"]]

    return dict(
        __key__="llava-{}".format(raw["__key__"]),
        images=images,
        texts=json_item["conversations"],
        similarity_matrix=None,
    )


def part_filter_68(part: str) -> bool:
    # E.g. if your dataset contains jpeg, txt and json, but you won't use json,
    # remove it from the list, such that it is not decoded. If you need all, keep as is
    return part in ("json", "jpg")


# Loader for: /lustre/fsw/portfolios/llmservice/projects/llmservice_nlp_fm/datasets/nvlm/wdai/data/mmtab/processed
# This file was automatically generated by `nvgpt4 data prepare`.


def sample_loader_69(raw: dict) -> dict:  # Note: Images are already decoded to tensors
    json_item = raw["json"]
    images = [raw["jpg"]]

    return dict(
        __key__="llava-{}".format(raw["__key__"]),
        images=images,
        texts=json_item["conversations"],
        similarity_matrix=None,
    )


def part_filter_69(part: str) -> bool:
    # E.g. if your dataset contains jpeg, txt and json, but you won't use json,
    # remove it from the list, such that it is not decoded. If you need all, keep as is
    return part in ("jpg", "json")


# Loader for: /lustre/fsw/portfolios/llmservice/projects/llmservice_nlp_fm/datasets/nvlm/wdai/data/simchart9k/processed
# This file was automatically generated by `nvgpt4 data prepare`.


def sample_loader_70(raw: dict) -> dict:  # Note: Images are already decoded to tensors
    json_item = raw["json"]
    images = [raw["jpg"]]

    return dict(
        __key__="llava-{}".format(raw["__key__"]),
        images=images,
        texts=json_item["conversations"],
        similarity_matrix=None,
    )


def part_filter_70(part: str) -> bool:
    # E.g. if your dataset contains jpeg, txt and json, but you won't use json,
    # remove it from the list, such that it is not decoded. If you need all, keep as is
    return part in ("jpg", "json")


# Loader for: /lustre/fsw/portfolios/llmservice/projects/llmservice_nlp_fm/datasets/nvlm/wdai/data/llava-onevision/mapqa_processed
# This file was automatically generated by `nvgpt4 data prepare`.


def sample_loader_71(raw: dict) -> dict:  # Note: Images are already decoded to tensors
    json_item = raw["json"]
    images = [raw["jpg"]]

    return dict(
        __key__="llava-{}".format(raw["__key__"]),
        images=images,
        texts=json_item["conversations"],
        similarity_matrix=None,
    )


def part_filter_71(part: str) -> bool:
    # E.g. if your dataset contains jpeg, txt and json, but you won't use json,
    # remove it from the list, such that it is not decoded. If you need all, keep as is
    return part in ("jpg", "json")


# Loader for: /lustre/fsw/portfolios/llmservice/projects/llmservice_nlp_fm/datasets/nvlm/wdai/data/llava-onevision/vizwiz_processed
# This file was automatically generated by `nvgpt4 data prepare`.


def sample_loader_72(raw: dict) -> dict:  # Note: Images are already decoded to tensors
    json_item = raw["json"]
    images = [raw["jpg"]]

    return dict(
        __key__="llava-{}".format(raw["__key__"]),
        images=images,
        texts=json_item["conversations"],
        similarity_matrix=None,
    )


def part_filter_72(part: str) -> bool:
    # E.g. if your dataset contains jpeg, txt and json, but you won't use json,
    # remove it from the list, such that it is not decoded. If you need all, keep as is
    return part in ("jpg", "json")


# Loader for: /lustre/fsw/portfolios/llmservice/projects/llmservice_nlp_fm/datasets/nvlm/wdai/data/augmentations/gpt_infovqa
# This file was automatically generated by `nvgpt4 data prepare`.


def sample_loader_73(raw: dict) -> dict:  # Note: Images are already decoded to tensors
    json_item = raw["json"]

    img = Image.open(io.BytesIO(raw["img"]))
    images = [img]

    return dict(
        __key__="llava-{}".format(raw["__key__"]),
        images=images,
        texts=json_item["conversations"],
        similarity_matrix=None,
    )


def part_filter_73(part: str) -> bool:
    # E.g. if your dataset contains jpeg, txt and json, but you won't use json,
    # remove it from the list, such that it is not decoded. If you need all, keep as is
    return part in ("json", "img")


# Loader for: /lustre/fsw/portfolios/llmservice/projects/llmservice_nlp_fm/datasets/nvlm/wdai/data/augmentations/viquae
# This file was automatically generated by `nvgpt4 data prepare`.


def sample_loader_74(raw: dict) -> dict:  # Note: Images are already decoded to tensors
    json_item = raw["json"]

    img = Image.open(io.BytesIO(raw["img"]))
    images = [img]

    return dict(
        __key__="llava-{}".format(raw["__key__"]),
        images=images,
        texts=json_item["conversations"],
        similarity_matrix=None,
    )


def part_filter_74(part: str) -> bool:
    # E.g. if your dataset contains jpeg, txt and json, but you won't use json,
    # remove it from the list, such that it is not decoded. If you need all, keep as is
    return part in ("json", "img")


# Loader for: /lustre/fsw/portfolios/llmservice/projects/llmservice_nlp_fm/datasets/captioning/ccs_recaptioned/webdataset
# This file was automatically generated by `nvgpt4 data prepare`.


def sample_loader_75(raw: dict) -> dict:  # Note: Images are already decoded to tensors
    if "text" in raw:
        caption = raw["text"]
    else:
        caption = raw["json"]["caption"]
    return dict(
        __key__=raw["__key__"],
        image=raw["jpg"],  # expected type: torch.Tensor
        caption=caption,  # expected type: str
    )


def part_filter_75(part: str) -> bool:
    # E.g. if your dataset contains jpeg, txt and json, but you won't use json,
    # remove it from the list, such that it is not decoded. If you need all, keep as is
    return part in ("json", "jpg", "text")


# Loader for: /lustre/fsw/portfolios/llmservice/projects/llmservice_nlp_fm/datasets/captioning/laion115m-clean
# This file was automatically generated by `nvgpt4 data prepare`.


def sample_loader_76(raw: dict) -> dict:  # Note: Images are already decoded to tensors
    if "text" in raw:
        caption = raw["text"]
    else:
        caption = raw["json"]["caption"]
    return dict(
        __key__=raw["__key__"],
        image=raw["jpg"],  # expected type: torch.Tensor
        caption=caption,  # expected type: str
    )


def part_filter_76(part: str) -> bool:
    # E.g. if your dataset contains jpeg, txt and json, but you won't use json,
    # remove it from the list, such that it is not decoded. If you need all, keep as is
    return part in ("json", "jpg", "text")


# Loader for: /lustre/fsw/portfolios/llmservice/projects/llmservice_nlp_fm/datasets/nvlm/wdai/data/dvqa_full/processed_pt
# This file was automatically generated by `nvgpt4 data prepare`.


def sample_loader_77(raw: dict) -> dict:  # Note: Images are already decoded to tensors
    json_item = raw["json"]

    total = len(json_item["conversations"]) // 2
    idx = random.randrange(total)  # noqa: F821
    human = json_item["conversations"][idx * 2]
    out = json_item["conversations"][idx * 2 + 1]

    return dict(
        __key__=raw["__key__"],
        image=raw["jpg"],
        context=human["value"].replace("<image>\n", ""),
        answers=out["value"],
        answer_weights=None,
    )


def part_filter_77(part: str) -> bool:
    # E.g. if your dataset contains jpeg, txt and json, but you won't use json,
    # remove it from the list, such that it is not decoded. If you need all, keep as is
    return part in ("json", "jpg")


# Loader for: /lustre/fsw/portfolios/llmservice/projects/llmservice_nlp_fm/datasets/nvlm/wdai/data/docmatix/processed_pt
# This file was automatically generated by `nvgpt4 data prepare`.


def sample_loader_78(raw: dict) -> dict:  # Note: Images are already decoded to tensors
    json_item = raw["json"]

    total = len(json_item["conversations"]) // 2
    idx = random.randrange(total)  # noqa: F821
    human = json_item["conversations"][idx * 2]
    out = json_item["conversations"][idx * 2 + 1]

    return dict(
        __key__=raw["__key__"],
        image=raw["jpg"],
        context=human["value"].replace("<image>\n", ""),
        answers=out["value"],
        answer_weights=None,
    )


def part_filter_78(part: str) -> bool:
    # E.g. if your dataset contains jpeg, txt and json, but you won't use json,
    # remove it from the list, such that it is not decoded. If you need all, keep as is
    return part in ("json", "jpg")


# Loader for: /lustre/fsw/portfolios/llmservice/projects/llmservice_nlp_fm/datasets/vqa/VQAv2/stage1


def sample_loader_79(raw: dict) -> dict:  # Note: Images are already decoded to tensors
    j = raw["json"]
    if "answer" in j:
        answers = [a[0] for a in j["answer"][0]]
        answer_weights = torch.Tensor([float(a[1]) for a in j["answer"][0]])
    else:
        answers = None
        answer_weights = None

    return dict(
        __key__=raw["__key__"],
        image=raw["jpg"],  # expected type: torch.Tensor
        context=j["question"],  # expected type: str
        answers=answers,  # expected type: typing.List[str]
        answer_weights=answer_weights,  # expected type: typing.Union[torch.Tensor, NoneType]
    )


def part_filter_79(part: str) -> bool:
    # Filter for parts required by the sample_loader
    return part in ("jpg", "json")


# Loader for: /lustre/fsw/portfolios/llmservice/projects/llmservice_nlp_fm/datasets/vqa/Visual_Genome
# This file was automatically generated by `nvgpt4 data prepare`.


def sample_loader_80(raw: dict) -> dict:  # Note: Images are already decoded to tensors
    return dict(
        __key__=raw["__key__"],
        image=raw["jpg"],  # expected type: torch.Tensor
        context=raw["json"]["question"],  # expected type: str
        answers=raw["json"]["answer"],  # expected type: typing.Union[typing.List[str], NoneType], default: None
        answer_weights=None,  # expected type: typing.Union[torch.Tensor, NoneType], default: None
    )


def part_filter_80(part: str) -> bool:
    return part in ("json", "jpg")


# Loader for: /lustre/fsw/portfolios/llmservice/projects/llmservice_nlp_fm/datasets/nvlm/wdai/data/pdfa-eng-wds/processed_word_len_300
# This file was automatically generated by `nvgpt4 data prepare`.


def sample_loader_81(raw: dict) -> dict:  # Note: Images are already decoded to tensors
    j = raw["json"]
    return dict(
        image=raw["jpg"],  # expected type: torch.Tensor
        text=" ".join(j["lines"]["text"]),  # expected type: str
    )


def part_filter_81(part: str) -> bool:
    # E.g. if your dataset contains jpeg, txt and json, but you won't use json,
    # remove it from the list, such that it is not decoded. If you need all, keep as is
    return part in ("jpg", "json")


# Loader for: /lustre/fsw/portfolios/llmservice/projects/llmservice_nlp_fm/datasets/nvlm/wdai/data/textocr/processed
# This file was automatically generated by `nvgpt4 data prepare`.


def sample_loader_82(raw: dict) -> dict:  # Note: Images are already decoded to tensors
    j = raw["json"]

    return dict(
        __key__=raw["__key__"],
        image=raw["jpg"],
        text=j["text"],
        words_boxes=j["bbox_1k_normalized"],
    )


def part_filter_82(part: str) -> bool:
    # E.g. if your dataset contains jpeg, txt and json, but you won't use json,
    # remove it from the list, such that it is not decoded. If you need all, keep as is
    return part in ("jpg", "json")


# Loader for: /lustre/fsw/portfolios/llmservice/projects/llmservice_nlp_fm/datasets/nvlm/wdai/data/coco-text/processed
# This file was automatically generated by `nvgpt4 data prepare`.


def sample_loader_83(raw: dict) -> dict:
    j = raw["json"]

    return dict(
        __key__=raw["__key__"],
        image=raw["jpg"],
        text=j["text"],
        words_boxes=j["bbox_1k_normalized"],
    )


def part_filter_83(part: str) -> bool:
    # E.g. if your dataset contains jpeg, txt and json, but you won't use json,
    # remove it from the list, such that it is not decoded. If you need all, keep as is
    return part in ("json", "jpg")


# Loader for: /lustre/fsw/portfolios/llmservice/projects/llmservice_nlp_fm/datasets/nvlm/wdai/data/ArT/processed
# This file was automatically generated by `nvgpt4 data prepare`.


def sample_loader_84(raw: dict) -> dict:  # Note: Images are already decoded to tensors
    j = raw["json"]

    return dict(
        __key__=raw["__key__"],
        image=raw["jpg"],
        text=j["text"],
        words_boxes=j["bbox_1k_normalized"],
    )


def part_filter_84(part: str) -> bool:
    # E.g. if your dataset contains jpeg, txt and json, but you won't use json,
    # remove it from the list, such that it is not decoded. If you need all, keep as is
    return part in ("json", "jpg")


# Loader for: /lustre/fsw/portfolios/llmservice/projects/llmservice_nlp_fm/datasets/nvlm/wdai/data/ReCTs/processed
# This file was automatically generated by `nvgpt4 data prepare`.


def sample_loader_85(raw: dict) -> dict:  # Note: Images are already decoded to tensors
    j = raw["json"]

    return dict(__key__=raw["__key__"], image=raw["jpg"], text=j["text"], words_boxes=j["quad_1k_normalized"])


def part_filter_85(part: str) -> bool:
    # E.g. if your dataset contains jpeg, txt and json, but you won't use json,
    # remove it from the list, such that it is not decoded. If you need all, keep as is
    return part in ("json", "jpg")


# Loader for: /lustre/fsw/portfolios/llmservice/projects/llmservice_nlp_fm/datasets/nvlm/wdai/data/lsvt/processed
# This file was automatically generated by `nvgpt4 data prepare`.


def sample_loader_86(raw: dict) -> dict:  # Note: Images are already decoded to tensors
    j = raw["json"]

    return dict(
        __key__=raw["__key__"],
        image=raw["jpg"],
        text=j["text"],
        words_boxes=j["bbox_1k_normalized"],
    )


def part_filter_86(part: str) -> bool:
    # E.g. if your dataset contains jpeg, txt and json, but you won't use json,
    # remove it from the list, such that it is not decoded. If you need all, keep as is
    return part in ("jpg", "json")


# Loader for: /lustre/fsw/portfolios/llmservice/projects/llmservice_nlp_fm/datasets/nvlm/wdai/data/RCTW/processed
# This file was automatically generated by `nvgpt4 data prepare`.


def sample_loader_87(raw: dict) -> dict:  # Note: Images are already decoded to tensors
    j = raw["json"]

    quad = j["quad"]
    quad = [val for point in quad for val in point]

    return dict(
        image=raw["jpg"],  # expected type: torch.Tensor
        text=j["text"],  # expected type: str
        words_boxes=quad,  # expected type: typing.Optional[torch.Tensor], default: None
    )


def part_filter_87(part: str) -> bool:
    # E.g. if your dataset contains jpeg, txt and json, but you won't use json,
    # remove it from the list, such that it is not decoded. If you need all, keep as is
    return part in ("json", "jpg")


# Loader for: /lustre/fsw/portfolios/llmservice/projects/llmservice_nlp_fm/datasets/nvlm/wdai/data/coco-text/processed_multi
# This file was automatically generated by `nvgpt4 data prepare`.


def sample_loader_88(raw: dict) -> dict:  # Note: Images are already decoded to tensors
    j = raw["json"]
    return dict(
        __key__=raw["__key__"],
        image=raw["jpg"],
        text="",
        words_boxes=j["bboxes_1k_normalized"],
        words_text=j["texts"],
    )


def part_filter_88(part: str) -> bool:
    # E.g. if your dataset contains jpeg, txt and json, but you won't use json,
    # remove it from the list, such that it is not decoded. If you need all, keep as is
    return part in ("json", "jpg")


# Loader for: /lustre/fsw/portfolios/llmservice/projects/llmservice_nlp_fm/datasets/nvlm/wdai/data/textocr/processed_multi
# This file was automatically generated by `nvgpt4 data prepare`.


def sample_loader_89(raw: dict) -> dict:
    j = raw["json"]
    return dict(
        __key__=raw["__key__"],
        image=raw["jpg"],
        text="",
        words_boxes=j["bboxes_1k_normalized"],
        words_text=j["texts"],
    )


def part_filter_89(part: str) -> bool:
    # E.g. if your dataset contains jpeg, txt and json, but you won't use json,
    # remove it from the list, such that it is not decoded. If you need all, keep as is
    return part in ("jpg", "json")


# Loader for: /lustre/fsw/portfolios/llmservice/projects/llmservice_nlp_fm/datasets/nvlm/wdai/data/ReCTs/processed_multi
# This file was automatically generated by `nvgpt4 data prepare`.


def sample_loader_90(raw: dict) -> dict:  # Note: Images are already decoded to tensors
    j = raw["json"]
    return dict(
        __key__=raw["__key__"],
        image=raw["jpg"],
        text="",
        words_boxes=j["quads_1k_normalized"],
        words_text=j["texts"],
    )


def part_filter_90(part: str) -> bool:
    # E.g. if your dataset contains jpeg, txt and json, but you won't use json,
    # remove it from the list, such that it is not decoded. If you need all, keep as is
    return part in ("json", "jpg")


# Loader for: /lustre/fsw/portfolios/llmservice/projects/llmservice_nlp_fm/datasets/vqa/VQAv2/stage1


def sample_loader_91(raw: dict) -> dict:  # Note: Images are already decoded to tensors
    j = raw["json"]
    if "answer" in j:
        answers = [a[0] for a in j["answer"][0]]
        answer_weights = torch.Tensor([float(a[1]) for a in j["answer"][0]])
    else:
        answers = None
        answer_weights = None

    return dict(
        __key__=raw["__key__"],
        image=raw["jpg"],  # expected type: torch.Tensor
        context=j["question"],  # expected type: str
        answers=answers,  # expected type: typing.List[str]
        answer_weights=answer_weights,  # expected type: typing.Union[torch.Tensor, NoneType]
    )


def part_filter_91(part: str) -> bool:
    # Filter for parts required by the sample_loader
    return part in ("jpg", "json")


# Dataset -> Sample Loader Mapping
dataset_loader_mapping = {
    "coco_train_val_restval": {
        "sample_loader": "sample_loader_0",
        "part_filter": "part_filter_0",
        "data_class": "CaptioningWebdataset",
        "data_weight": 0.01,
    },
    "extended-sci/data/merged/CoT": {
        "sample_loader": "sample_loader_1",
        "part_filter": "part_filter_1",
        "data_class": "SimilarityInterleavedWebdataset",
        "data_weight": 0.006,
    },
    "extended-sci/data/merged/single-choice": {
        "sample_loader": "sample_loader_2",
        "part_filter": "part_filter_2",
        "data_class": "SimilarityInterleavedWebdataset",
        "data_weight": 0.004,
    },
    "extended-sci/data/extended-sci-3/CoT": {
        "sample_loader": "sample_loader_3",
        "part_filter": "part_filter_3",
        "data_class": "SimilarityInterleavedWebdataset",
        "data_weight": 0.0006,
    },
    "extended-sci/data/extended-sci-3/single-choice": {
        "sample_loader": "sample_loader_4",
        "part_filter": "part_filter_4",
        "data_class": "SimilarityInterleavedWebdataset",
        "data_weight": 0.0004,
    },
    "nvlm/wdai/data/SceMQA_processed": {
        "sample_loader": "sample_loader_5",
        "part_filter": "part_filter_5",
        "data_class": "SimilarityInterleavedWebdataset",
        "data_weight": 0.0006,
    },
    "nvlm/wdai/data/vqa_collection_doc_text_st_chart_scale_textbook_LRV_Screen": {
        "sample_loader": "sample_loader_6",
        "part_filter": "part_filter_6",
        "data_class": "VQAWebdataset",
        "data_weight": 0.08,
    },
    "nvlm/wdai/data/plotqa/processed": {
        "sample_loader": "sample_loader_7",
        "part_filter": "part_filter_7",
        "data_class": "VQAWebdataset",
        "data_weight": 0.095,
    },
    "nvlm/wdai/data/clevr-math/processed": {
        "sample_loader": "sample_loader_8",
        "part_filter": "part_filter_8",
        "data_class": "VQAWebdataset",
        "data_weight": 0.02,
    },
    "nvlm/wdai/data/MMC-Instruction/processed": {
        "sample_loader": "sample_loader_9",
        "part_filter": "part_filter_9",
        "data_class": "VQAWebdataset",
        "data_weight": 0.07,
    },
    "nvlm/wdai/data/ocrvqa/processed": {
        "sample_loader": "sample_loader_10",
        "part_filter": "part_filter_10",
        "data_class": "VQAWebdataset",
        "data_weight": 0.06,
    },
    "nvlm/wdai/data/dude/processed": {
        "sample_loader": "sample_loader_11",
        "part_filter": "part_filter_11",
        "data_class": "VQAWebdataset",
        "data_weight": 0.01,
    },
    "nvlm/wdai/data/VisualMRC/processed": {
        "sample_loader": "sample_loader_12",
        "part_filter": "part_filter_12",
        "data_class": "VQAWebdataset",
        "data_weight": 0.015,
    },
    "nvlm/wdai/data/mcvqa_collection_scienceqa_ai2d_geoqaplus_geometry3k_tqa": {
        "sample_loader": "sample_loader_13",
        "part_filter": "part_filter_13",
        "data_class": "MultiChoiceVQAWebdataset",
        "data_weight": 0.025,
    },
    "nvlm/wdai/data/arxiv_qa/processed": {
        "sample_loader": "sample_loader_14",
        "part_filter": "part_filter_14",
        "data_class": "MultiChoiceVQAWebdataset",
        "data_weight": 0.02,
    },
    "nvlm/wdai/data/tabmwp/processed": {
        "sample_loader": "sample_loader_15",
        "part_filter": "part_filter_15",
        "data_class": "MultiChoiceVQAWebdataset",
        "data_weight": 0.015,
    },
    "nvlm/wdai/data/ocr_vqa_aug/processed": {
        "sample_loader": "sample_loader_16",
        "part_filter": "part_filter_16",
        "data_class": "SimilarityInterleavedWebdataset",
        "data_weight": 0.055,
    },
    "nvlm/wdai/data/dvqa_full/processed": {
        "sample_loader": "sample_loader_17",
        "part_filter": "part_filter_17",
        "data_class": "SimilarityInterleavedWebdataset",
        "data_weight": 0.055,
    },
    "nvlm/wdai/data/LLaVA-v1.5_shuffle/no_refcoco_vg_ocrvqa": {
        "sample_loader": "sample_loader_18",
        "part_filter": "part_filter_18",
        "data_class": "SimilarityInterleavedWebdataset",
        "data_weight": 0.085,
    },
    "vqa/more_data/infographics_vqa/processed/train": {
        "sample_loader": "sample_loader_19",
        "part_filter": "part_filter_19",
        "data_class": "SimilarityInterleavedWebdataset",
        "data_weight": 0.01,
    },
    "nvlm/wdai/data/sharegpt4o/processed": {
        "sample_loader": "sample_loader_20",
        "part_filter": "part_filter_20",
        "data_class": "SimilarityInterleavedWebdataset",
        "data_weight": 0.02,
    },
    "nvlm/wdai/data/sparse_ocr_data/merged": {
        "sample_loader": "sample_loader_21",
        "part_filter": "part_filter_21",
        "data_class": "SimilarityInterleavedWebdataset",
        "data_weight": 0.045,
    },
    "nvlm/nayeonl/data/blendv4/MetaMathQA/processed/train_text_image": {
        "sample_loader": "sample_loader_22",
        "part_filter": "part_filter_22",
        "data_class": "SimilarityInterleavedWebdataset",
        "data_weight": 0.004,
    },
    "nvlm/nayeonl/data/blendv4/gsm8k/processed/train_text_image": {
        "sample_loader": "sample_loader_23",
        "part_filter": "part_filter_23",
        "data_class": "SimilarityInterleavedWebdataset",
        "data_weight": 0.003,
    },
    "nvlm/wdai/data/docmatix/processed": {
        "sample_loader": "sample_loader_24",
        "part_filter": "part_filter_24",
        "data_class": "SimilarityInterleavedWebdataset",
        "data_weight": 0.1,
    },
    "nvlm/wdai/data/bentham_hw_squad/processed": {
        "sample_loader": "sample_loader_25",
        "part_filter": "part_filter_25",
        "data_class": "SimilarityInterleavedWebdataset",
        "data_weight": 0.01,
    },
    "nvlm/wdai/data/WikiTableQA/processed": {
        "sample_loader": "sample_loader_26",
        "part_filter": "part_filter_26",
        "data_class": "SimilarityInterleavedWebdataset",
        "data_weight": 0.003,
    },
    "nvlm/wdai/data/figureqa/processed": {
        "sample_loader": "sample_loader_27",
        "part_filter": "part_filter_27",
        "data_class": "SimilarityInterleavedWebdataset",
        "data_weight": 0.01,
    },
    "nvlm/wdai/data/llava-onevision/ai2d_combined_processed": {
        "sample_loader": "sample_loader_28",
        "part_filter": "part_filter_28",
        "data_class": "SimilarityInterleavedWebdataset",
        "data_weight": 0.01,
    },
    "nvlm/wdai/data/llava-onevision/math_combined_processed": {
        "sample_loader": "sample_loader_29",
        "part_filter": "part_filter_29",
        "data_class": "SimilarityInterleavedWebdataset",
        "data_weight": 0.035,
    },
    "nvlm/wdai/data/llava-onevision/robut_combined_processed": {
        "sample_loader": "sample_loader_30",
        "part_filter": "part_filter_30",
        "data_class": "SimilarityInterleavedWebdataset",
        "data_weight": 0.01,
    },
    "nvlm/wdai/data/llava-onevision/llavar_20k_processed": {
        "sample_loader": "sample_loader_31",
        "part_filter": "part_filter_31",
        "data_class": "SimilarityInterleavedWebdataset",
        "data_weight": 0.007,
    },
    "nvlm/wdai/data/llava-onevision/tallyqa_processed": {
        "sample_loader": "sample_loader_32",
        "part_filter": "part_filter_32",
        "data_class": "SimilarityInterleavedWebdataset",
        "data_weight": 0.02,
    },
    "nvlm/wdai/data/llava-onevision/ureader_ie_processed": {
        "sample_loader": "sample_loader_33",
        "part_filter": "part_filter_33",
        "data_class": "SimilarityInterleavedWebdataset",
        "data_weight": 0.007,
    },
    "nvlm/wdai/data/llava-onevision/visual7w_processed": {
        "sample_loader": "sample_loader_34",
        "part_filter": "part_filter_34",
        "data_class": "SimilarityInterleavedWebdataset",
        "data_weight": 0.006,
    },
    "nvlm/wdai/data/llava-onevision/mavis_math_rule_geo_processed": {
        "sample_loader": "sample_loader_35",
        "part_filter": "part_filter_35",
        "data_class": "SimilarityInterleavedWebdataset",
        "data_weight": 0.01,
    },
    "nvlm/wdai/data/llava-onevision/ureader_kg_processed": {
        "sample_loader": "sample_loader_36",
        "part_filter": "part_filter_36",
        "data_class": "SimilarityInterleavedWebdataset",
        "data_weight": 0.005,
    },
    "nvlm/wdai/data/llava-onevision/ureader_qa_processed": {
        "sample_loader": "sample_loader_37",
        "part_filter": "part_filter_37",
        "data_class": "SimilarityInterleavedWebdataset",
        "data_weight": 0.02,
    },
    "nvlm/wdai/data/ocr_multi_collection_cocotext_textocr_ReCTs": {
        "sample_loader": "sample_loader_38",
        "part_filter": "part_filter_38",
        "data_class": "OCRWebdataset",
        "data_weight": 0.01,
    },
    "nvlm/wdai/data/pdfa-eng-wds/processed_word_len_500": {
        "sample_loader": "sample_loader_39",
        "part_filter": "part_filter_39",
        "data_class": "OCRWebdataset",
        "data_weight": 0.015,
    },
    "nvlm/wdai/data/llava-onevision/super_clevr_processed": {
        "sample_loader": "sample_loader_40",
        "part_filter": "part_filter_40",
        "data_class": "SimilarityInterleavedWebdataset",
        "data_weight": 0.007,
    },
    "nvlm/wdai/data/llava-onevision/icon_qa_processed": {
        "sample_loader": "sample_loader_41",
        "part_filter": "part_filter_41",
        "data_class": "SimilarityInterleavedWebdataset",
        "data_weight": 0.009,
    },
    "nvlm/wdai/data/augmentations/chartqa_aug": {
        "sample_loader": "sample_loader_42",
        "part_filter": "part_filter_42",
        "data_class": "SimilarityInterleavedWebdataset",
        "data_weight": 0.005,
    },
    "nvlm/wdai/data/augmentations/gpt_chartqa": {
        "sample_loader": "sample_loader_43",
        "part_filter": "part_filter_43",
        "data_class": "SimilarityInterleavedWebdataset",
        "data_weight": 0.006,
    },
    "nvlm/wdai/data/augmentations/gpt_docvqa": {
        "sample_loader": "sample_loader_44",
        "part_filter": "part_filter_44",
        "data_class": "SimilarityInterleavedWebdataset",
        "data_weight": 0.006,
    },
    "nvlm/wdai/data/augmentations/docvqa_text": {
        "sample_loader": "sample_loader_45",
        "part_filter": "part_filter_45",
        "data_class": "SimilarityInterleavedWebdataset",
        "data_weight": 0.006,
    },
    "nvlm/wdai/data/augmentations/textvqa_text": {
        "sample_loader": "sample_loader_46",
        "part_filter": "part_filter_46",
        "data_class": "SimilarityInterleavedWebdataset",
        "data_weight": 0.008,
    },
    "nvlm/wdai/data/augmentations/i2s-musicsheet": {
        "sample_loader": "sample_loader_47",
        "part_filter": "part_filter_47",
        "data_class": "SimilarityInterleavedWebdataset",
        "data_weight": 0.0005,
    },
    "nvlm/wdai/data/augmentations/music": {
        "sample_loader": "sample_loader_48",
        "part_filter": "part_filter_48",
        "data_class": "SimilarityInterleavedWebdataset",
        "data_weight": 0.007,
    },
    "nvlm/wdai/data/augmentations/invoice": {
        "sample_loader": "sample_loader_49",
        "part_filter": "part_filter_49",
        "data_class": "SimilarityInterleavedWebdataset",
        "data_weight": 0.002,
    },
    "nvlm/wdai/data/augmentations/k12": {
        "sample_loader": "sample_loader_50",
        "part_filter": "part_filter_50",
        "data_class": "SimilarityInterleavedWebdataset",
        "data_weight": 0.019,
    },
    "nvlm/wdai/data/augmentations/MTVQA": {
        "sample_loader": "sample_loader_51",
        "part_filter": "part_filter_51",
        "data_class": "SimilarityInterleavedWebdataset",
        "data_weight": 0.007,
    },
    "nvlm/wdai/data/augmentations/VisualWebInstruct": {
        "sample_loader": "sample_loader_52",
        "part_filter": "part_filter_52",
        "data_class": "SimilarityInterleavedWebdataset",
        "data_weight": 0.028,
    },
    "nvlm/wdai/data/augmentations/financeqa": {
        "sample_loader": "sample_loader_53",
        "part_filter": "part_filter_53",
        "data_class": "SimilarityInterleavedWebdataset",
        "data_weight": 0.005,
    },
    "nvlm/wdai/data/augmentations/docreason": {
        "sample_loader": "sample_loader_54",
        "part_filter": "part_filter_54",
        "data_class": "SimilarityInterleavedWebdataset",
        "data_weight": 0.004,
    },
    "nvlm/wdai/data/augmentations/gpt_mtwi": {
        "sample_loader": "sample_loader_55",
        "part_filter": "part_filter_55",
        "data_class": "SimilarityInterleavedWebdataset",
        "data_weight": 0.005,
    },
    "nvlm/wdai/data/augmentations/geos_gpt": {
        "sample_loader": "sample_loader_56",
        "part_filter": "part_filter_56",
        "data_class": "SimilarityInterleavedWebdataset",
        "data_weight": 0.0001,
    },
    "nvlm/wdai/data/augmentations/cauldron_vistext": {
        "sample_loader": "sample_loader_57",
        "part_filter": "part_filter_57",
        "data_class": "SimilarityInterleavedWebdataset",
        "data_weight": 0.005,
    },
    "nvlm/wdai/data/augmentations/memes": {
        "sample_loader": "sample_loader_58",
        "part_filter": "part_filter_58",
        "data_class": "SimilarityInterleavedWebdataset",
        "data_weight": 0.005,
    },
    "nvlm/wdai/data/augmentations/gpt_roadtext": {
        "sample_loader": "sample_loader_59",
        "part_filter": "part_filter_59",
        "data_class": "SimilarityInterleavedWebdataset",
        "data_weight": 0.0002,
    },
    "nvlm/wdai/data/augmentations/indoor_qa": {
        "sample_loader": "sample_loader_60",
        "part_filter": "part_filter_60",
        "data_class": "SimilarityInterleavedWebdataset",
        "data_weight": 0.001,
    },
    "nvlm/wdai/data/augmentations/colpali": {
        "sample_loader": "sample_loader_61",
        "part_filter": "part_filter_61",
        "data_class": "SimilarityInterleavedWebdataset",
        "data_weight": 0.007,
    },
    "nvlm/wdai/data/augmentations/pmc_vqa": {
        "sample_loader": "sample_loader_62",
        "part_filter": "part_filter_62",
        "data_class": "SimilarityInterleavedWebdataset",
        "data_weight": 0.01,
    },
    "nvlm/wdai/data/augmentations/pathvqa": {
        "sample_loader": "sample_loader_63",
        "part_filter": "part_filter_63",
        "data_class": "SimilarityInterleavedWebdataset",
        "data_weight": 0.004,
    },
    "nvlm/wdai/data/augmentations/sciqa": {
        "sample_loader": "sample_loader_64",
        "part_filter": "part_filter_64",
        "data_class": "SimilarityInterleavedWebdataset",
        "data_weight": 0.027,
    },
    "nvlm/wdai/data/augmentations/chinese_meme": {
        "sample_loader": "sample_loader_65",
        "part_filter": "part_filter_65",
        "data_class": "SimilarityInterleavedWebdataset",
        "data_weight": 0.001,
    },
    "nvlm/wdai/data/augmentations/gpt_hiertext": {
        "sample_loader": "sample_loader_66",
        "part_filter": "part_filter_66",
        "data_class": "SimilarityInterleavedWebdataset",
        "data_weight": 0.003,
    },
    "nvlm/wdai/data/augmentations/cauldron_cocoqa": {
        "sample_loader": "sample_loader_67",
        "part_filter": "part_filter_67",
        "data_class": "SimilarityInterleavedWebdataset",
        "data_weight": 0.007,
    },
    "nvlm/wdai/data/cmm-math/processed": {
        "sample_loader": "sample_loader_68",
        "part_filter": "part_filter_68",
        "data_class": "SimilarityInterleavedWebdataset",
        "data_weight": 0.001,
    },
    "nvlm/wdai/data/mmtab/processed": {
        "sample_loader": "sample_loader_69",
        "part_filter": "part_filter_69",
        "data_class": "SimilarityInterleavedWebdataset",
        "data_weight": 0.008,
    },
    "nvlm/wdai/data/simchart9k/processed": {
        "sample_loader": "sample_loader_70",
        "part_filter": "part_filter_70",
        "data_class": "SimilarityInterleavedWebdataset",
        "data_weight": 0.001,
    },
    "nvlm/wdai/data/llava-onevision/mapqa_processed": {
        "sample_loader": "sample_loader_71",
        "part_filter": "part_filter_71",
        "data_class": "SimilarityInterleavedWebdataset",
        "data_weight": 0.005,
    },
    "nvlm/wdai/data/llava-onevision/vizwiz_processed": {
        "sample_loader": "sample_loader_72",
        "part_filter": "part_filter_72",
        "data_class": "SimilarityInterleavedWebdataset",
        "data_weight": 0.002,
    },
    "nvlm/wdai/data/augmentations/gpt_infovqa": {
        "sample_loader": "sample_loader_73",
        "part_filter": "part_filter_73",
        "data_class": "SimilarityInterleavedWebdataset",
        "data_weight": 0.001,
    },
    "nvlm/wdai/data/augmentations/viquae": {
        "sample_loader": "sample_loader_74",
        "part_filter": "part_filter_74",
        "data_class": "SimilarityInterleavedWebdataset",
        "data_weight": 0.0005,
    },
    "captioning/ccs_recaptioned/webdataset": {
        "sample_loader": "sample_loader_75",
        "part_filter": "part_filter_75",
        "data_class": "CaptioningWebdataset",
        "data_weight": 0.2,
    },
    "captioning/laion115m-clean": {
        "sample_loader": "sample_loader_76",
        "part_filter": "part_filter_76",
        "data_class": "CaptioningWebdataset",
        "data_weight": 0.579,
    },
    "nvlm/wdai/data/dvqa_full/processed_pt": {
        "sample_loader": "sample_loader_77",
        "part_filter": "part_filter_77",
        "data_class": "VQAWebdataset",
        "data_weight": 0.02,
    },
    "nvlm/wdai/data/docmatix/processed_pt": {
        "sample_loader": "sample_loader_78",
        "part_filter": "part_filter_78",
        "data_class": "VQAWebdataset",
        "data_weight": 0.02,
    },
    "vqa/VQAv2/stage1": {
        "sample_loader": "sample_loader_91",
        "part_filter": "part_filter_91",
        "data_class": "VQAWebdataset",
        "data_weight": 1.0,
    },
    "vqa/Visual_Genome": {
        "sample_loader": "sample_loader_80",
        "part_filter": "part_filter_80",
        "data_class": "VQAWebdataset",
        "data_weight": 0.01,
    },
    "nvlm/wdai/data/pdfa-eng-wds/processed_word_len_300": {
        "sample_loader": "sample_loader_81",
        "part_filter": "part_filter_81",
        "data_class": "OCRWebdataset",
        "data_weight": 0.08,
    },
    "nvlm/wdai/data/textocr/processed": {
        "sample_loader": "sample_loader_82",
        "part_filter": "part_filter_82",
        "data_class": "OCRWebdataset",
        "data_weight": 0.02,
    },
    "nvlm/wdai/data/coco-text/processed": {
        "sample_loader": "sample_loader_83",
        "part_filter": "part_filter_83",
        "data_class": "OCRWebdataset",
        "data_weight": 0.002,
    },
    "nvlm/wdai/data/ArT/processed": {
        "sample_loader": "sample_loader_84",
        "part_filter": "part_filter_84",
        "data_class": "OCRWebdataset",
        "data_weight": 0.001,
    },
    "nvlm/wdai/data/ReCTs/processed": {
        "sample_loader": "sample_loader_85",
        "part_filter": "part_filter_85",
        "data_class": "OCRWebdataset",
        "data_weight": 0.001,
    },
    "nvlm/wdai/data/lsvt/processed": {
        "sample_loader": "sample_loader_86",
        "part_filter": "part_filter_86",
        "data_class": "OCRWebdataset",
        "data_weight": 0.005,
    },
    "nvlm/wdai/data/RCTW/processed": {
        "sample_loader": "sample_loader_87",
        "part_filter": "part_filter_87",
        "data_class": "OCRWebdataset",
        "data_weight": 0.001,
    },
    "nvlm/wdai/data/coco-text/processed_multi": {
        "sample_loader": "sample_loader_88",
        "part_filter": "part_filter_88",
        "data_class": "OCRWebdataset",
        "data_weight": 0.0003,
    },
    "nvlm/wdai/data/textocr/processed_multi": {
        "sample_loader": "sample_loader_89",
        "part_filter": "part_filter_89",
        "data_class": "OCRWebdataset",
        "data_weight": 0.0004,
    },
    "nvlm/wdai/data/ReCTs/processed_multi": {
        "sample_loader": "sample_loader_90",
        "part_filter": "part_filter_90",
        "data_class": "OCRWebdataset",
        "data_weight": 0.0003,
    },
}


def get_sample_loader(path):
    """Returns the correct sample_loader function for a dataset."""
    if path not in dataset_loader_mapping:
        path = data_path_mapping(path)
    assert path in dataset_loader_mapping, f"path {path} not in dataset_loader_mapping"
    return globals().get(dataset_loader_mapping.get(path, {}).get("sample_loader"))


def get_part_filter(path):
    """Returns the correct part_filter function for a dataset."""
    if path not in dataset_loader_mapping:
        path = data_path_mapping(path)
    assert path in dataset_loader_mapping, f"path {path} not in dataset_loader_mapping"
    return globals().get(dataset_loader_mapping.get(path, {}).get("part_filter"))


def get_data_class(path):
    """Returns the correct data_class for a dataset."""
    if path not in dataset_loader_mapping:
        path = data_path_mapping(path)

    assert path in dataset_loader_mapping, f"path {path} not in dataset_loader_mapping"
    return dataset_loader_mapping[path]["data_class"]
